source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

link_with 'Marvel App', 'Marvel AppTests'

pod 'HanekeSwift', '~> 0.10'
pod 'SVProgressHUD', '~> 1.1'
pod 'AFNetworking', '~> 3.0'